name: CI
# name of workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    build:
        # now here we have the one job called build
        runs-on: ubuntu-latest
        # this jobs will run on ubuntu runner, all of these are github hosted runner

        steps:
        - uses: actions/checkout@v3
            # this task is telling the github action workflow to download the content of you repo to the current workspace
            # we might need to have this action in every github action unless it is for non CI/CD operation

        - name: Run a one-line script
            run: echo Hello, world!

        - name: Run a multi-line script
            run: |
            echo Add other actions to build,
            echo test, and deploy your project.
    test:
        # here we can see that we can create many jobs
        runs-on: ubuntu-latest
        # Note: whenever you have multiple jobs like in this case they run simultaneously
        # so, if we will run the action workflow then it will 'build' the job and 'test' the job in parallel
        # so, this might be use full when you have different independent task to do
        # however, you want to chain jobs at that time we will use 'needs'
        needs: [build]
        # now here this 'test' job will wait for build job to succeed and then will start

        steps:
        - run: xxxx
